"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, MapPin, Sparkles } from "lucide-react";
import { getSupabase } from "@/lib/supabase/client";

type Report={month_start:string;snapshot:{name:string;outside_score:number;active_days:number;verified_outings:number;quests:number;crew_activity:number;lagos_rank:number;daily_streak:number;outing_streak:number}};
export default function SharedReport(){const {token}=useParams<{token:string}>();const [report,setReport]=useState<Report|null>(null);useEffect(()=>{let alive=true;const sb=getSupabase();if(sb)void sb.rpc("get_monthly_report",{p_token:token}).then(({data})=>{if(alive&&data)setReport(data as Report)});return()=>{alive=false}},[token]);if(!report)return <div className="grid h-full place-items-center"><p className="hint">LOADING REPORT…</p></div>;const s=report.snapshot;return <div className="h-full overflow-y-auto px-4 pb-8"><header className="pad-top pb-5"><Link href="/" className="inline-flex items-center gap-2 font-mono text-[9px] font-bold text-dim"><ArrowLeft size={14}/> HOPPAZ</Link></header><article className="mx-auto max-w-md overflow-hidden rounded-xl border border-orange bg-ink-2 shadow-sheet"><div className="bg-orange p-5 text-ink"><p className="font-mono text-[9px] font-bold tracking-[0.2em]">HOPPAZ · OUTSIDE REPORT</p><h1 className="mt-2 font-display text-3xl font-black">{s.name} was outside.</h1><p className="mt-2 flex items-center gap-2 font-mono text-xs font-bold"><CalendarDays size={14}/>{new Date(`${report.month_start}T12:00:00`).toLocaleDateString("en-NG",{month:"long",year:"numeric",timeZone:"Africa/Lagos"})}</p></div><div className="grid grid-cols-2 gap-px bg-line"><Stat icon={<Sparkles size={17}/>} label="OUTSIDE SCORE" value={s.outside_score}/><Stat icon={<Sparkles size={17}/>} label="LAGOS RANK" value={s.lagos_rank}/><Stat icon={<MapPin size={17}/>} label="VERIFIED OUTINGS" value={s.verified_outings}/><Stat icon={<CalendarDays size={17}/>} label="ACTIVE DAYS" value={s.active_days}/><Stat icon={<Sparkles size={17}/>} label="QUESTS DONE" value={s.quests}/><Stat icon={<Sparkles size={17}/>} label="CREW MOMENTS" value={s.crew_activity}/></div><div className="p-4"><p className="font-display font-black">The city looks better from out here.</p><p className="hint mt-1">A month of nights, people and places across Lagos.</p><Link href="/" className="btn mt-4 w-full">GET OUT THERE</Link></div></article></div>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="bg-ink p-4"><div className="flex items-center gap-2 text-orange">{icon}<span className="seclabel">{label}</span></div><p className="mt-2 font-display text-3xl font-black tabular-nums">{value}</p></div>}
