import Link from "next/link";
import { ArrowLeft } from "lucide-react";

const support=process.env.NEXT_PUBLIC_SUPPORT_EMAIL;
export default function PrivacyPage(){return <div className="h-full overflow-y-auto px-4 pb-8"><header className="pad-top pb-5"><Link href="/me" className="inline-flex items-center gap-2 font-mono text-[9px] font-bold text-dim"><ArrowLeft size={14}/> BACK</Link><h1 className="mt-4 font-display text-2xl font-black">Your data on Hoppaz</h1><p className="seclabel mt-1.5">Plain-language privacy notice · Lagos</p></header><div className="prose-hoppaz space-y-5">
  <section><h2>What Hoppaz stores</h2><p>Your anonymous account has an internal ID. Your profile may include the name, home area and avatar you choose. Hoppaz stores event check-ins, quest and reward claims, crew memberships, messages, reports, and event photos you submit.</p></section>
  <section><h2>Location</h2><p>If you allow device location, Hoppaz sends your coordinates to verify proximity to an event or drop. The verification functions use those coordinates to return a distance decision; they do not write the submitted coordinates into the activity ledger. The app may remember your selected location on this device. Your exact device coordinates are not shown to other people. Your selected home area and profile are used for the features you enable, such as crew pins.</p></section>
  <section><h2>Photos and messages</h2><p>Event photos are private while awaiting review. Approved photos are displayed in Hoppaz with time-limited image access. Chat messages are visible in their room or private thread; moderators may resolve reported content and can map anonymous room aliases to an account when investigating abuse. Blocking and reporting are available in chat.</p></section>
  <section><h2>Sharing</h2><p>Monthly report cards use a private, hard-to-guess link. Anyone with that link can view the report snapshot. Do not share it if you want to keep those activity details private.</p></section>
  <section><h2>Hosting and partners</h2><p>Hoppaz uses Supabase for account, database, realtime and image storage services, and Vercel to host the app. When you redeem a partner reward, you may show its claim code to that partner so they can honour it. Hoppaz does not sell profile or location data.</p></section>
  <section><h2>Your choices</h2><p>You can edit your display name, home area and avatar. You can remove your account from the Me screen; this deletes the profile, associated activity, crew data, chat messages, shared report links, and stored event photos from Hoppaz systems.</p></section>
  <section><h2>Contact and privacy requests</h2><p>{support?<>For access, correction, deletion or privacy questions, contact <a href={`mailto:${support}`}>{support}</a>.</>:"A public support email must be configured before launch so people can contact Hoppaz about privacy requests."}</p><p className="hint mt-2">This notice describes the current product behavior. The Hoppaz owner should review and complete it, including controller identity, retention periods, and contact details, before public launch.</p></section>
</div><p className="hint mt-6">See the <Link href="/community" className="text-orange underline">community rules</Link>.</p></div>}
